export ZSH="/Users/prasanna/.oh-my-zsh"
ZSH_THEME="robbyrussell"

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

HIST_STAMPS="dd/mm/yyyy"

plugins=(
git
rails
colorize
zsh-syntax-highlighting
zsh-autosuggestions
)

ZSH_DISABLE_COMPFIX=true
source $ZSH/oh-my-zsh.sh

# -----------------------------------------------
# Make vi default editor, vi related settings

# http://unix.stackexchange.com/questions/44115/how-do-i-perform-a-reverse-history-search-in-zshs-vi-mode/273672#273672?newreg=26e81cf912814bd590410b408c30851a
set -o vi

bindkey "^R" history-incremental-search-backward

# To distinguish between insert mode and normal mode in zsh vi
function zle-line-init zle-keymap-select {
   VIM_PROMPT="%{$fg_bold[yellow]%} [% NORMAL]%  %{$reset_color%}"
   RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/} $EPS1"
   zle reset-prompt
}

 zle -N zle-line-init
 zle -N zle-keymap-select
# Increase the switching time between insert and normal mode in vim

 autoload edit-command-line
 zle -N edit-command-line
 bindkey -M vicmd v edit-command-line

 export KEYTIMEOUT=1

 export LC_ALL=en_US.UTF-8
 export LANG=en_US.UTF-8
 export EDITOR=vi
# -----------------------------------------------

# Enable key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

source ~/.zsh-helpers/functions
source ~/.zsh-helpers/alias

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# Kubectl alias
alias k=kubectl
